# Generated by Django 2.1.1 on 2018-11-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='test_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='summary.Experiment', verbose_name='试验名称'),
            preserve_default=False,
        ),
    ]
