# Generated by Django 2.1.1 on 2018-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20181105_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_fieldcharacter',
            name='hairy_color',
            field=models.CharField(choices=[('无茸毛', '无茸毛'), ('灰色', '灰色'), ('棕色', '棕色')], max_length=5, verbose_name='茸毛色'),
        ),
    ]
